on:
    push:
        tags:
            - '0.*'

permissions:
    packages: write

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0

        -
            name: Set up Go
            uses: actions/setup-go@v4
            with:
                go-version: 1.22.3
        - 
            name: Init library
            run: |
                go mod download
                sudo mkdir -p $(go env GOMODCACHE)/github.com/jmoney/tokenizers@v0.7.4/lib
                sudo mkdir -p $(go env GOMODCACHE)/github.com/jmoney/tokenizers@v0.7.4/lib/darwin
                sudo mkdir -p $(go env GOMODCACHE)/github.com/jmoney/tokenizers@v0.7.4/lib/linux

                curl -fsSL "https://github.com/jmoney/tokenizers/releases/download/v0.7.4/libtokenizers.darwin-arm64.tar.gz" | tar xvz
                sudo mv ./libtokenizers.a $(go env GOMODCACHE)/github.com/jmoney/tokenizers@v0.7.4/lib/darwin/libtokenizers.a

                curl -fsSL "https://github.com/jmoney/tokenizers/releases/download/v0.7.4/libtokenizers.linux-arm64.tar.gz" | tar xvz
                sudo mv ./libtokenizers.a $(go env GOMODCACHE)/github.com/jmoney/tokenizers@v0.7.4/lib/linux/libtokenizers.a
        -
            name: Login to Docker
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GH_TOKEN }}

        - name: Release
          run: |
            docker run --rm -e CGO_ENABLED=1 -e GITHUB_TOKEN=${{ secrets.GH_TOKEN }}\
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v "$(go env GOMODCACHE):/root/go/pkg/mod" \
                -v `pwd`:/go/src/tokenizer-utils \
                -w /go/src/tokenizer-utils \
                ghcr.io/goreleaser/goreleaser-cross:v1.21.10 --clean