on:
    push:
        branches:
            - 'main'

permissions:
    contents: write

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
        -
            name: Set up Go
            uses: actions/setup-go@v4

        -
            name: Download libtokenizers
            run:
                curl -fsSL "https://github.com/daulet/tokenizers/releases/latest/download/libtokenizers.darwin-arm64.tar.gz" | tar xvz
                mv ./libtokenizers.a /go/pkg/mod/github.com/daulet/tokenizers@0.7.1/libtokenizers.a
        -
            name: Run GoReleaser
            uses: goreleaser/goreleaser-action@v5
            with:
            # either 'goreleaser' (default) or 'goreleaser-pro'
                distribution: goreleaser
                # 'latest', 'nightly', or a semver
                version: '~> v1'
                args: build --snapshot --clean
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}